# Site settings
# in the templates available like {{ site.myvariable }}.
title: Alpine Homes - Bed and Breakfast
email: rashim.dhir@gmail.com
brand: Alpine Homes - Bread and Breakfast
headline: 
description: > # this means to ignore newlines until "baseurl:"
  New Site
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://example.com" # the base hostname & protocol for your site
copyright: 2017 Alpine Homes, Inc. All Rights Reserved.

# Build settings
markdown: kramdown

# Account ids
snapwidget: 247552

# Contacts
email: rashim.dhir@gmail.com
phone: +91 9999999999

# Tracking
googleAnalitycsID: UA-83933844-1

